name: chatbot_app
description: A Flutter chat bot application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.2.0
  shared_preferences: ^2.2.0
  openai_api: ^0.3.7
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.8.5
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  # Supabase packages
  supabase_flutter: ^2.3.4
  supabase: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/chat_bg.png
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
